version: "3.1"

services:

  node:
    build:
      context: ./
      dockerfile: ./docker/node/Dockerfile
    container_name: vitta-assessment-dev
    working_dir: /application
    volumes:
      - .:/application
    command: npm start
    ports:
      - 3333:3333

  mysql:
    image: mysql:5.7
    container_name: vitta-assessment-mysql
    working_dir: /application
    volumes:
      - .:/application
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    env_file:
      - .env
    ports:
      - "7779:3306"
